Align table query parameters with Trace Compass constants
theia-ide/tsp-typescript-client pull request #16
Opened 2021-01-13 23:30 UTC by PatrickTasse

Signed-off-by: Patrick Tasse <patrick.tasse@gmail.com>

2021-01-14 19:13 UTC, PatrickTasse commented
I didn't notice that the parameter keys were specified in the body text paragraph in https://theia-ide.github.io/trace-server-protocol/#operation/getLines. I was looking at the 'parameters' description below and the 'Payload' example.

The keys are listed somewhere else in the source TSP but it doesn't show in this web version.

Nevertheless I would suggest to change also the TSP documentation to align with these keys. We should also find a way to update the documentation so that each different query can have its own description of the parameters that apply to it.

2021-01-14 20:54 UTC, bhufmann commented
> I didn't notice that the parameter keys were specified in the body text paragraph in https://theia-ide.github.io/trace-server-protocol/#operation/getLines. I was looking at the 'parameters' description below and the 'Payload' example.
> 
> The keys are listed somewhere else in the source TSP but it doesn't show in this web version.
> 
> Nevertheless I would suggest to change also the TSP documentation to align with these keys. We should also find a way to update the documentation so that each different query can have its own description of the parameters that apply to it.

These keys should be defined in the TSP and the implementation here needs to be aligned. I see that the web viewer of the TSP is not best when it comes to formatting as well as showing the schema instead of the example. 

Maybe update the title of the PR since we don't want to align to Trace Compass internal implementation. Maybe something along the lines " ... align with TSP ..." or make "... make keys consistent with other keys ...".

In any case, I agree the TSP documentation needs to be updated.

2021-01-15 15:56 UTC, MatthewKhouzam commented on src/models/query/query-helper.ts
> +    public static readonly REQUESTED_COLUMN_IDS_KEY = 'requested_table_column_ids';
Should the constant be "REQUESTED_TABLE_COLUMN_IDS_KEY"

2021-01-15 16:00 UTC, tahini commented
> 
> These keys should be defined in the TSP and the implementation here needs to be aligned. I see that the web viewer of the TSP is not best when it comes to formatting as well as showing the schema instead of the example.
> 

+1 This should align with the TSP and the TSP should not align with whatever naming we gave in TC, but make sense from a protocol implementer/consumer point of view. TSP may need to be updated first.

2021-01-15 16:16 UTC, MatthewKhouzam requested changes
The more I think of it, the more I think we shouldn't change the TSP to be tracecompass dependant.

If we improve the tsp that's fine, but we need to be agnostic first.

2021-01-15 16:28 UTC, PatrickTasse commented
TSP is currently inconsistent, here is where the alternative keys are listed:

https://github.com/theia-ide/trace-server-protocol/blob/master/API.yaml#L1904

However the "_key" suffixes are wrong there...

2021-01-15 16:46 UTC, tahini commented
FTR, I did a "TSP alignment" phase recently (see https://github.com/theia-ide/trace-server-protocol/pull/27), relating to model response data (I did not really touch the query parameters  then). My un-discussed and maybe dictatorial rule of thumb was to name to fields in camelCase and remove superfluous keywords (it's data being passed after all), so 'startTime' becomes simply 'start'.

In the trace server, I just wrote custom serializers to change TC field names into the TSP fields. No change required to TC code or API changes.

Something similar can be done for the requests. It would be normal that a server implementing a protocol needs to map the protocol's parameters to its internal equivalent of those.

2021-01-15 19:51 UTC, PatrickTasse commented
It was pointed out to me that according to this patch https://git.eclipse.org/r/143076, the parameter keys were meant to be updated in the TSP to the new ones I use in this commit. I guess the TSP update was not complete.

It has been suggested to update the TSP documentation first, then align to the new TSP parameter keys with this commit. I'll make a commit on the TSP.

2021-01-20 21:19 UTC, MatthewKhouzam approved these changes
Now it works!

2021-01-20 21:19 UTC, merged