Serialize and deserialize timestamps as strings
theia-ide/tsp-typescript-client pull request #28
Opened 2021-09-02 21:17 UTC by PatrickTasse

Fields that are known to be timestamps or durations are serialized and
deserialized as strings.

This is done to avoid loss of precision in JavaScript 'number' type for
values above Number.MAX_SAFE_INTEGER (2^53 - 1).

The trace-server is expected to support receiving those timestamps as
strings.

The client can handle receiving timestamps as string or number.

The models are updated to use 'bigint' type instead of 'number' for
these fields. When receiving timestamps, the string or number value will
be converted to a BigInt.

Signed-off-by: Patrick Tasse <patrick.tasse@ericsson.com>

2021-09-02 22:11 UTC, paul-marechal commented on src/protocol/tsp-client-response.ts
> +            }) as T;
Would it better to pass `reviver?: (key: string, value: unknown) => any` as a constructor parameter, and pass the proper conversion method when receiving responses?

2021-09-02 22:11 UTC, paul-marechal commented on src/protocol/rest-client.ts
> +        const replacer = (key, value) => (typeof value === 'bigint') ? value.toString() : value;
The `reviver` method could be specified here and passed to the `TspClientResponse`?

2021-09-03 14:31 UTC, PatrickTasse commented on src/protocol/rest-client.ts
> +        const replacer = (key, value) => (typeof value === 'bigint') ? value.toString() : value;
Thanks for the suggestion!

2021-09-03 14:31 UTC, PatrickTasse commented on src/protocol/tsp-client-response.ts
> +            }) as T;
Thanks for the suggestion!

2021-09-03 14:57 UTC, bhufmann requested changes

2021-09-03 14:57 UTC, bhufmann commented on src/protocol/rest-client.ts
> +    private static readonly BIGINT_FIELDS = ['start', 'end', 'time', 'duration', 'startTime', 'endTime'];
This basically means, that they are reserved words and have special treatment. Would they need to be described in the TSP specification? Also, if we choose to go that route, there should be only one reserved word, that describes "start" (i.e. not having both "start" and "startTime").

2021-09-03 14:57 UTC, bhufmann commented on src/protocol/rest-client.ts
> +        const jsonBody: string = JSON.stringify(body, replacer);
The TSP specification will be changed so that strings are used for timestamp values. Any other int64 values in the TSP will be still sent as a number and the Javascript side will loose precision if the values are too big and don't fit into a floating point number. 

If we decide to change the TSP to use strings, the Trace Compass server and all clients (typescript, and python clients) need to be changed. So, this would need to be done soon. Maybe there are other options? 

I found npm library: https://www.npmjs.com/package/json-bigint that could be explored

2021-09-03 15:58 UTC, paul-marechal commented on src/protocol/rest-client.ts
> +        const jsonBody: string = JSON.stringify(body, replacer);
To me there seems to be multiple avenues:

1. Use `json-bigint` to not change anything during serialization because of Node's limitation.
    - Treat every number as `bigint` in JS: this way no extra processing is required during deserialization.
    - Don't treat every number as `bigint`: you need to keep a mapping of what will need to be converted to `bigint` if it is parsed as `number` because < MAX_SAFE_INTEGER.
2. Do not use `json-bigint` but you'll need to encode `int64` values as `string` or any other format, and make sure that the deserializers know which field to convert back.

If I understand correctly, there's no precision issue in JS when dealing with `float64` right? Only `int64` are a problem?

2021-09-10 19:24 UTC, PatrickTasse commented on src/models/query/query-helper.ts
> +            result[i] = start + BigInt(Math.round(i * stepSize));
Should be Math.floor(), otherwise at nanosecond zoom level the data changes in the middle of two ticks.

2021-09-16 17:18 UTC, marco-miller commented on src/models/query/query-helper.ts
> +     * @param requestedTimes Array of requested times
I think this specific rename refactoring doesn't relate to the commit at hand; could have been another one.

2021-09-16 17:21 UTC, marco-miller commented on src/models/query/query-helper.ts
> +            start = tmp;
Should this case be flagged towards the caller, instead of being (albeit nicely) compensated in here?

2021-09-16 17:23 UTC, marco-miller commented on src/models/query/query-helper.ts
> -        const stepSize: number = Math.abs(end - start) / (nb - 1);
1. Maybe this abs call implies revisiting depending on my previous question.
2. Could be the same also for the below min and max calls but not sure.

2021-09-16 17:31 UTC, marco-miller commented on src/protocol/rest-client.ts
> +                    }
Replace lines 49-52 with this below?

```
}
// "1234567890123456789n" => 1234567890123456900
return Number(matchArray[1]);
```

2021-09-17 19:40 UTC, PatrickTasse commented on src/models/query/query-helper.ts
> +            start = tmp;
I guess the method already supported that case, with the use of abs(), min() and max() below in the old code. I tried to refactor to avoid the use of these methods (which did not exist for bigint). I didn't want to introduce an new error case for the callers to have to handle.

2021-09-17 19:42 UTC, PatrickTasse commented on src/models/query/query-helper.ts
> +     * @param requestedTimes Array of requested times
I changed the method signature so I fixed the parameter name at the same time.

2021-09-20 15:01 UTC, PatrickTasse commented on src/protocol/rest-client.ts
> +                    }
I think there is value for the code reader to distinguish between "if (condition) return early else continue" and "return either this or that" so I have never agreed with that lint/sonar rule... ;)

2021-09-20 16:03 UTC, marco-miller approved these changes

2021-09-20 16:04 UTC, marco-miller commented
Pending @bhufmann's and @paul-marechal's comment threads I believe.

2021-09-21 15:57 UTC, PatrickTasse commented on src/protocol/rest-client.ts
> +        const jsonBody: string = JSON.stringify(body, replacer);
With the latest code update TSP is not affected. The BigInt are converted to strings only temporarily inside the tsp-typescript-client library.

2021-09-21 16:02 UTC, PatrickTasse commented on src/protocol/rest-client.ts
> +    private static readonly BIGINT_FIELDS = ['start', 'end', 'time', 'duration', 'startTime', 'endTime'];
With the latest code these fields have special treatment only within the tsp-typescript-client library. We only have to identify which fields are 'bigint' within the library's own models. If a large number would not be identified properly, it would be received and treated as a number (with loss of precision).

2021-09-27 15:07 UTC, bhufmann requested changes
Small update to avoid division by 0.

2021-09-27 15:07 UTC, bhufmann commented on src/protocol/rest-client.ts
> +    private static readonly BIGINT_FIELDS = ['start', 'end', 'time', 'duration', 'startTime', 'endTime'];
Ok we can consolidate the strings once the TSP is more consistent.

2021-09-27 15:07 UTC, bhufmann commented on src/models/query/query-helper.ts
> +        const stepSize: number = Number(end - start) / (nb - 1);
division by 0 possible here. Maybe return always 'start' when 'nb' is 1 (and make sure start < end)

2021-09-27 19:50 UTC, bhufmann approved these changes
Looks good to me. Thanks for the contribution.

2021-10-05 18:47 UTC, merged