Align client classes with the TSP specification
theia-ide/tsp-typescript-client pull request #4
Opened 2020-08-04 21:41 UTC by tahini

Fixes #3

Signed-off-by: Geneviève Bastien <gbastien+lttng@versatic.net>

2020-09-18 17:56 UTC, bhufmann requested changes

2020-09-18 17:56 UTC, bhufmann commented on src/models/entry.ts
> +    hasRowModel?: boolean;
update to generic name in TSP. I think it's hasData

2020-09-28 20:20 UTC, tahini commented
It matches the master of the trace-server-protocol­ as of today. It will be a breaking change for the trace extension and will need a matching patch in the trace server. I'm working on it, once the builds are fixed there!

2020-09-30 14:26 UTC, bhufmann reviewed
@tahini,  one question below. Also, we need  to make sure that we will merge this when all related patches are ready.

2020-09-30 14:26 UTC, bhufmann commented on src/protocol/tsp-client.ts
> +        return await RestClient.post<GenericResponse<EntryModel<TimeGraphEntry>>>(url, parameters);
@tahini You are removing the generic types here and below. I'm not sure about the implications. Does it mean that the server has to send a TimeGraphEntry in the response and can't send something like (MyEntry extends TimeGraphEntry)? It would be more strict, right?

2020-09-30 14:49 UTC, tahini commented on src/protocol/tsp-client.ts
> +        return await RestClient.post<GenericResponse<EntryModel<TimeGraphEntry>>>(url, parameters);
Indeed! It is my understanding from a protocol point of view that we should not send random fields  that are not documented, but rather let the protocol provide a way to describe the potential arbitrary fields (like name, tooltip, datatype, description, etc), so that implementation can have one generic way to handle them. The consumers should not have to know about all the various entry types, so yeah, the server will have to send a TimeGraphEntry with extra fields described as labels. It would be more strict, but for a good cause I think.

That is the reason behind this issue here: https://github.com/theia-ide/trace-server-protocol/issues/35 Let me know what you think

2020-10-15 14:00 UTC, bhufmann approved these changes
Looks good to me. Works with corresponding patches in trace server and theia-trace-extension

2020-10-16 12:59 UTC, tahini commented
Thanks for the review, I'll merge when all the components are ready to merge (the theia-trace-extension one will need to be updated once this is in to link to the new next version of this packages)

2020-10-20 12:13 UTC, merged