Catch errors in RestClient
theia-ide/tsp-typescript-client pull request #50
Opened 2022-02-24 23:17 UTC by PatrickTasse

Catch errors thrown from the HTTP request and return a 503 response.

Catch errors thrown from JSON parser and normalizer and return a
response without model.

Change-Id: I75d6a8019254b6db1c07a91e67a6e8eb438ba57d
Signed-off-by: Patrick Tasse <patrick.tasse@ericsson.com>

2022-03-08 15:33 UTC, Rodrigoplp-work requested changes

2022-03-08 19:58 UTC, PatrickTasse commented on tsp-typescript-client/src/protocol/rest-client.ts
> +            return new TspClientResponse(response.text, response.status, response.statusText);
The jsonParse can throw an error if the trace-server doesn't return a proper object as an entity. In some failure cases it sends an error status code along with a string failure message as the entity, this does not parse. In this case we want to send the orignal failure message as the response text.

The normalizer can also fail in a few cases: server sends a too large number to fit in expected Number, or sends a floating-point number with decimals that does not construct as expected BigInt. Here we just pass along the server response but without a parsed model. I'm not sure if it's the correct behavior but I would be worried about changing the server's response?

2022-03-08 20:52 UTC, bhufmann commented on tsp-typescript-client/src/protocol/rest-client.ts
> +            const parsed = this.jsonParse(response.text);
here we assume that the text is always json, but is that true? In the request, we ask for json, but the error code is not 200, does the still need to reply a json? Depending on the answer of these questions we need to do the implementation. Maybe you need to check the HTTP protocol spec for that.

Secondly, let's say the return code is 200 and the server returns not a json string as requested, i.e. server doesn't comply with the spec or the message got corrupted. In that case, our client implementation still needs to be robust. I'm not sure what to return as status code then.

For the non-successful case, does the request body have to be json as well, or can it be a string and even empty? 
If it cannot be a regular string, then the Trace Compass server implementation is incorrect and needs to be fixed. Also, the empty string case needs to be looked at.

Nevertheless, the code here needs to be robust to handle non-compliant replies and return an appropriate reply.

2022-03-08 20:52 UTC, bhufmann commented on tsp-typescript-client/src/protocol/rest-client.ts
> +            return new TspClientResponse(response.text, response.status, response.statusText);
Not sure either, what to do here when the normalizer fails. With this implementation, the error is just swallowed. It should be visible somewhere so that there is information for trouble-shooting. Can we log it? Or have an error handler interface?

2022-03-14 20:19 UTC, PatrickTasse commented on tsp-typescript-client/src/protocol/rest-client.ts
> +            const parsed = this.jsonParse(response.text);
I found that our trace server always returns Content-Type = application/json, even when the entity is a string. However I was able to have the trace server build an error response with MediaType set to plain/text, and this is received in the response headers.

I would propose to attempt to parse the response only when the Content-Type is application/json. If a plain text string is (incorrectly) identified as application/json in the header, we could catch the error here, log an error to the console and continue with a null response model.

We should then modify the trace-server to set plain/text content type for error responses that contain a string entity.

2022-03-14 20:24 UTC, PatrickTasse commented on tsp-typescript-client/src/protocol/rest-client.ts
> +            return new TspClientResponse(response.text, response.status, response.statusText);
When the normalizer fails I believe it is an indication that the trace-server has sent a model that does not respect the protocol.

I would propose to catch the error, log an error and continue with a null response model.

2022-03-14 20:34 UTC, PatrickTasse commented on tsp-typescript-client/src/protocol/rest-client.ts
>      ): Promise<TspClientResponse<Deserialized<T>>> {
The application currently does not handle a rejected promise, so the error propagates as an uncaught error. I would propose that we try to always return a successful promise, as the application should always check if the response has a successful status code and a valid response model.

2022-03-14 20:55 UTC, bhufmann commented on tsp-typescript-client/src/protocol/rest-client.ts
>      ): Promise<TspClientResponse<Deserialized<T>>> {
Ok

2022-03-14 20:55 UTC, bhufmann commented on tsp-typescript-client/src/protocol/rest-client.ts
> +            const parsed = this.jsonParse(response.text);
Sounds good. Nonetheless you wrap the whole parsing in a try-catch to avoid propagating an unexpected error.

2022-03-14 20:55 UTC, bhufmann commented on tsp-typescript-client/src/protocol/rest-client.ts
> +            return new TspClientResponse(response.text, response.status, response.statusText);
Sounds good (that's what I proposed above too :-))

2022-03-15 18:02 UTC, bhufmann requested changes
It looks good and I tried with some modified server code. Could you please add some unit test to verify different error cases and headers?

2022-03-15 20:34 UTC, Rodrigoplp-work approved these changes

2022-03-16 12:59 UTC, bhufmann approved these changes
Looks good to me. Thanks!

2022-03-16 14:29 UTC, merged